### ISSUE TITLE
Fade-out Glitch

### ISSUE THREAD

**Issue by Qrbaker** [alatsombath/Fountain-of-Colors#1]
Entire visualizer randomly flickers between opaque and invisible, regardless of "fountain effects" setting. This is paired with a requirement for an unusually high sensitivity (55 decibels) required to see any effect at all.

[Here is a video of the issue](http://gfycat.com/InfamousThirstyJellyfish)

**Comment by alatsombath** [comment]
Released a fix in 3.4.10. This doesn't have to do with the fountain effects, but is caused when the visualizer disables the audio measures (as a workaround to a potential CPU leak) and hides itself if no sound is playing. It seems that different devices reach the threshold more erratically, so a timeout has been added to delay disabling the audio measures.

As for the sensitivity, you should adjust the volume slider in your media player to the maximum if it isn't already. It's also possible that your music library might have files with extremely low gain, in this case see if your media player has a filter to "normalize" the sound levels.

**Comment by Qrbaker** [comment]
Seems to have been caused by the audio player I was using, a Windows port of Clementine. Problem fixed after switching to AIMP.
