### ISSUE TITLE
Min. height not working

### ISSUE THREAD

**Issue by cubeslice** [alatsombath/Fountain-of-Colors#10]
Hello! I just want to start by saying that this is probably the best visualizer on Rainmeter. However, when I went to try and set the minimum height, the visualizer would stop moving. As you can see here: 
![image](https://user-images.githubusercontent.com/35668016/43865014-4546d26a-9b2f-11e8-9c97-492086ee4205.png)
The visualizer is moving. But, when I set the minimum height to any number:
![image](https://user-images.githubusercontent.com/35668016/43865054-6758ce80-9b2f-11e8-8a87-8418164b3b95.png)
It just stops moving. Is there any way I can fix this? Thank you.

**Comment by alatsombath** [comment]
Hi, can you try the new update v3.8?

**Comment by cubeslice** [comment]
I'll try it when I get home

**Comment by cubeslice** [comment]
Great! The new update fixed it and added other improvements. Thanks.
