### ISSUE TITLE
FoC loaded but not appearing

### ISSUE THREAD

**Issue by GMatrixGames** [alatsombath/Fountain-of-Colors#6]
Hello,
I was following a tutorial on how to make your desktop cleaner,
and they used FoC for music. But when I installed it with Rainmeter, it says loaded, but it doesn't show up on my desktop at all, not even over other windows.

Please help,
GMatrixGames

**Comment by GMatrixGames** [comment]
It was a bug with sensitivity. It's now working!

**Comment by alatsombath** [comment]
Was the sensitivity too low, or something else entirely? It may help resolve an issue in another thread
